CIA openapi3 spec
MapColonies/CIA pull request #3
Opened 2020-11-17 10:49 UTC by vitaligi

Closing #1

2020-11-18 08:37 UTC, syncush requested changes

2020-11-18 08:37 UTC, syncush commented on openapi3-cia.yaml
> +    email: 54726763+vitaligi@users.noreply.github.com
We can use 
```suggest
  contact:
    name: MapColonies
    email: mapcolonies@gmail.com
```

2020-11-18 08:37 UTC, syncush commented on openapi3-cia.yaml
> +      operationId: getCores
lets use `kebab-case` instead `camelCase` for `operationId`

2020-11-18 08:37 UTC, syncush commented on openapi3-cia.yaml
> +          description: a unique core identifier (preferably md5)
why do we need two `id`s? 
I suggest
```suggest
        id:
          type: string
          format: uuid
```

2020-11-18 08:37 UTC, syncush commented on openapi3-cia.yaml
> +      - coreId
I think all fields are required

2020-11-18 08:37 UTC, syncush commented on openapi3-cia.yaml
> +          maxLength: 3000
I think all of our responses should be `snake_case` and not `camelCase`, wdyt?

2020-11-18 08:37 UTC, syncush commented on openapi3-cia.yaml
> +          maxLength: 3000
I think 3000 is a bit too much, maybe we should start with 255

2020-11-18 08:37 UTC, syncush commented on openapi3-cia.yaml
> +      in: header
Let's drop auth for now since we do not know what auth method we will use in the future?
it will be resolved later.

2020-11-18 08:37 UTC, syncush commented on openapi3-cia.yaml
> +      - code
I think we can drop the `code` field since we have the HTTP response error code. no need for extra field

2020-11-18 08:37 UTC, syncush commented on openapi3-cia.yaml
> +                $ref: '#/components/schemas/ErrorModel'
I disagree that default error means an `Unexpected error` has occurred.
what if the `coreId` was not according to format? then it is a `400 bad request` - an expected error

2020-11-18 08:37 UTC, syncush commented on openapi3-cia.yaml
> +          description: a unique core identifier (preferably md5)
I think we should use `uuid v4` for an `id`

2020-11-18 08:37 UTC, syncush commented on openapi3-cia.yaml
> +        - core
I think we should specify all the expected errors 
for example for delete we know the set of errors are:
1. 400 Bad Request
2. 404 Resource not found
3. 500 Internal server error

2020-11-18 08:37 UTC, syncush commented on openapi3-cia.yaml
> +        default: v1
Better if we drop it for now, when I am changing from 443 to 80 it doesn't turn from `https` to `http` and we still don't know how we are going to deploy the service yet.

2020-11-18 08:48 UTC, vitaligi commented on openapi3-cia.yaml
> +          description: a unique core identifier (preferably md5)
i left an `id` for the db management because i leave an option for multiple ids range allocations

2020-11-18 08:49 UTC, vitaligi commented on openapi3-cia.yaml
> +    email: 54726763+vitaligi@users.noreply.github.com
is it available email?

2020-11-18 09:00 UTC, vitaligi commented on openapi3-cia.yaml
> +      - coreId
agree, i will add readOnly to all fields except coreId

2020-11-18 09:01 UTC, syncush commented on openapi3-cia.yaml
> +    email: 54726763+vitaligi@users.noreply.github.com
yes

2020-11-18 09:03 UTC, syncush commented on openapi3-cia.yaml
> +          description: a unique core identifier (preferably md5)
I am not sure I understood you, can you elaborate?

2020-11-18 09:09 UTC, vitaligi commented on openapi3-cia.yaml
> +          maxLength: 3000
If we respond with a JSON object I think we should follow camelCase

2020-11-18 09:15 UTC, vitaligi commented on openapi3-cia.yaml
> +          maxLength: 3000
Perhaps over 9000?
Seriously, we don't know yet what details could be stored in notes, perhaps a description of some unusual allocation case...
For now we may set it to 255

2020-11-18 09:16 UTC, vitaligi commented on openapi3-cia.yaml
> +      in: header
done

2020-11-18 09:19 UTC, vitaligi commented on openapi3-cia.yaml
> +                $ref: '#/components/schemas/ErrorModel'
I agree, copied it and should have changed that
What is your description suggestion?

2020-11-18 09:25 UTC, vitaligi commented on openapi3-cia.yaml
> +          description: a unique core identifier (preferably md5)
Agreed, for `coreId`
done

2020-11-18 09:29 UTC, vitaligi commented on openapi3-cia.yaml
> +        default: v1
We could also comment this out

2020-11-18 09:30 UTC, vitaligi commented on openapi3-cia.yaml
> +      - code
done

2020-11-18 09:34 UTC, vitaligi commented on openapi3-cia.yaml
> +      operationId: getCores
Why do you prefer kebab-case?

2020-11-18 10:14 UTC, vitaligi commented on openapi3-cia.yaml
> +        - core
Ok, will get to it

2020-11-18 10:18 UTC, syncush commented on openapi3-cia.yaml
> +      operationId: getCores
If it is a camel case, one maybe would try to look for a function with the same name as the operationId since js function name convention is also camelCase

2020-11-18 10:20 UTC, syncush commented on openapi3-cia.yaml
> +        default: v1
OK, I don't mind to leave it as a comment

2020-11-18 11:38 UTC, vitaligi commented on openapi3-cia.yaml
> +    email: 54726763+vitaligi@users.noreply.github.com
done

2020-11-18 11:48 UTC, vitaligi commented on openapi3-cia.yaml
> +      operationId: getCores
https://swagger.io/docs/specification/paths-and-operations/
some of the usages of `operationId` is to indicate the responsible method in code, so if its JS then it should be camelCase

2020-11-18 12:17 UTC, vitaligi commented on openapi3-cia.yaml
> +        default: v1
done

2020-11-19 13:10 UTC, vitaligi commented on openapi3-cia.yaml
> +        - core
done

2020-11-22 11:27 UTC, syncush approved these changes

2020-11-22 11:28 UTC, merged